/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * School Management API
 * OpenAPI spec version: v1
 */
import type { StudentModel } from './studentModel';

export interface ApiResultStudentModelList {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: StudentModel[];
}
