/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * School Management API
 * OpenAPI spec version: v1
 */
import type { LoginModel } from './loginModel';

export interface ApiResultLoginModel {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: LoginModel;
}
