/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * School Management API
 * OpenAPI spec version: v1
 */
import type { ClassModel } from './classModel';

export interface ApiResultClassModel {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: ClassModel[];
}
