/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * School Management API
 * OpenAPI spec version: v1
 */
import type { BatchModel } from './batchModel';

export interface ApiResultBatchModel {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: BatchModel[];
}
