/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * School Management API
 * ### API flow (all modules)
 * | Action | HTTP | Route |
 * | Get All | GET | /api/{Controller}/Get |
 * | Get By ID | GET | /api/{Controller}/GetByID/{id} |
 * | Add | POST | /api/{Controller}/Add |
 * | Update | PUT | /api/{Controller}/Update |
 * | Delete | DELETE | /api/{Controller}/Delete/{id} |
 *
 * ### JWT
 * 1. POST /api/Login/Login → copy token
 * 2. Authorize in Swagger (paste token only)
 * 3. GET /api/Login/Profile to verify
 *
 * **Student:** yash@gmail.com / 123 | **Admin:** admin / admin123
 * OpenAPI spec version: v1
 */

export interface FeesUpdateRequest {
  studentID?: number;
  totalFees?: number;
  paidAmount?: number;
  pendingAmount?: number;
  /** @nullable */
  paymentDate?: string | null;
  /** @nullable */
  paymentMode?: string | null;
  /** @nullable */
  transactionNo?: string | null;
  /** @nullable */
  paymentStatus?: string | null;
  /** @nullable */
  remark?: string | null;
  addedBy?: number;
  feesID?: number;
  updatedBy?: number;
}
