/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * SchoolERP.API
 * ### JWT
 * 1. POST /api/Login/Login → copy token
 * 2. Authorize in Swagger (paste token only)
 * 3. GET /api/Login/Profile to verify
 *
 * **Student:** yash@gmail.com / 123 | **Admin:** admin / admin123
 * OpenAPI spec version: v1
 */

export interface FeesCollectModel {
  studentId?: number;
  amount?: number;
  /** @nullable */
  paymentMode?: string | null;
  /** @nullable */
  transactionRef?: string | null;
  /** @nullable */
  collectedBy?: number | null;
}
