/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * SchoolERP.API
 * ### JWT
 * 1. POST /api/Login/Login → copy token
 * 2. Authorize in Swagger (paste token only)
 * 3. GET /api/Login/Profile to verify
 *
 * **Student:** yash@gmail.com / 123 | **Admin:** admin / admin123
 * OpenAPI spec version: v1
 */

export * from './academicYearModel';
export * from './academicYearModelApiResponse';
export * from './academicYearModelListApiResponse';
export * from './adminGetParams';
export * from './adminModel';
export * from './admissionInquiriesParams';
export * from './attendanceAbsentStudentsParams';
export * from './attendanceMarkModel';
export * from './attendanceMonthlyReportParams';
export * from './attendanceReportParams';
export * from './batchModel';
export * from './batchModelApiResponse';
export * from './batchModelListApiResponse';
export * from './bloodGroupModel';
export * from './bloodGroupModelApiResponse';
export * from './bloodGroupModelListApiResponse';
export * from './bookIssueModel';
export * from './bookModel';
export * from './bookReturnModel';
export * from './categoryModel';
export * from './categoryModelApiResponse';
export * from './categoryModelListApiResponse';
export * from './classModel';
export * from './examModel';
export * from './examResultModel';
export * from './feesCollectModel';
export * from './feesPaymentHistoryParams';
export * from './feesPendingParams';
export * from './homeworkByClassParams';
export * from './homeworkModel';
export * from './homeworkSubmitModel';
export * from './importExportImportStudentsBody';
export * from './leaveApplicationModel';
export * from './leaveApproveModel';
export * from './leaveGetParams';
export * from './loginRequest';
export * from './loginResponseModel';
export * from './loginResponseModelApiResponse';
export * from './messageModel';
export * from './noticeGetParams';
export * from './noticeMessagesParams';
export * from './noticeModel';
export * from './objectApiResponse';
export * from './onlineInquiryModel';
export * from './parentGetParams';
export * from './parentModel';
export * from './razorpayOrderModel';
export * from './razorpayVerifyModel';
export * from './religionModel';
export * from './religionModelApiResponse';
export * from './religionModelListApiResponse';
export * from './reportsGetParams';
export * from './sectionModel';
export * from './sectionModelApiResponse';
export * from './sectionModelListApiResponse';
export * from './settingModel';
export * from './stringApiResponse';
export * from './studentGetPagedParams';
export * from './studentHistoryModel';
export * from './studentInquiryModel';
export * from './studentModel';
export * from './studentModelByID';
export * from './studentPanelAttendanceGetParams';
export * from './studentPanelAttendanceSummaryGetParams';
export * from './studentPanelExamResultDetailsGetParams';
export * from './studentPromotionModel';
export * from './studentTransportModel';
export * from './teacherGetParams';
export * from './teacherModel';
export * from './uploadDocumentBody';
export * from './uploadHomeworkBody';
export * from './uploadSchoolLogoBody';
export * from './uploadStudentPhotoBody';
export * from './uploadTeacherPhotoBody';
export * from './uplodedUploadDocumentBody';
export * from './uplodedUploadImageBody';
export * from './vehicleModel';
