/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * School Management API
 * ### API flow (all modules)
 * | Action | HTTP | Route |
 * | Get All | GET | /api/{Controller}/Get |
 * | Get By ID | GET | /api/{Controller}/GetByID/{id} |
 * | Add | POST | /api/{Controller}/Add |
 * | Update | PUT | /api/{Controller}/Update |
 * | Delete | DELETE | /api/{Controller}/Delete/{id} |
 *
 * ### JWT
 * 1. POST /api/Login/Login → copy token
 * 2. Authorize in Swagger (paste token only)
 * 3. GET /api/Login/Profile to verify
 *
 * **Student:** yash@gmail.com / 123 | **Admin:** admin / admin123
 * OpenAPI spec version: v1
 */

export * from './academicYearModel';
export * from './apiResult';
export * from './batchModel';
export * from './bloodGroupModel';
export * from './categoryModel';
export * from './classModel';
export * from './deleteApiClassDeleteClassParams';
export * from './deleteApiClassDeleteIdParams';
export * from './examDeleteRequest';
export * from './examInsertRequest';
export * from './examUpdateRequest';
export * from './feesDeleteRequest';
export * from './feesInsertRequest';
export * from './feesUpdateRequest';
export * from './forgotPasswordRequest';
export * from './leaveApplicationDeleteRequest';
export * from './leaveApplicationInsertRequest';
export * from './leaveApplicationUpdateRequest';
export * from './loginRequest';
export * from './moneyDeleteRequest';
export * from './moneyInsertRequest';
export * from './moneyUpdateRequest';
export * from './noticeDeleteRequest';
export * from './noticeInsertRequest';
export * from './noticeUpdateRequest';
export * from './notificationDeleteRequest';
export * from './notificationInsertRequest';
export * from './notificationUpdateRequest';
export * from './parentDeleteRequest';
export * from './parentInsertRequest';
export * from './parentsChangePasswordRequest';
export * from './parentUpdateRequest';
export * from './postApiUplodedUploadDocumentBody';
export * from './postApiUplodedUploadImageBody';
export * from './postApiUplodedUploadMultipleFilesBody';
export * from './problemDetails';
export * from './religionModel';
export * from './resultDeleteRequest';
export * from './resultInsertRequest';
export * from './resultUpdateRequest';
export * from './roleDeleteRequest';
export * from './roleInsertRequest';
export * from './roleRightsDeleteRequest';
export * from './roleRightsInsertRequest';
export * from './roleRightsUpdateRequest';
export * from './roleUpdateRequest';
export * from './sectionModel';
export * from './studentAttendanceDeleteRequest';
export * from './studentAttendanceInsertRequest';
export * from './studentAttendanceUpdateRequest';
export * from './studentChangePasswordRequest';
export * from './studentModel';
export * from './subjectDeleteRequest';
export * from './subjectInsertRequest';
export * from './subjectUpdateRequest';
export * from './teacherAttendanceDeleteRequest';
export * from './teacherAttendanceInsertRequest';
export * from './teacherAttendanceUpdateRequest';
export * from './teacherChangePasswordRequest';
export * from './teacherDeleteRequest';
export * from './teacherInsertRequest';
export * from './teacherUpdateRequest';
export * from './userDeleteRequest';
export * from './userDeviceTokenDeleteRequest';
export * from './userDeviceTokenInsertRequest';
export * from './userDeviceTokenUpdateRequest';
export * from './userInsertRequest';
export * from './userUpdateRequest';
