/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * School Management API
 * ### API flow (all modules)
 * | Action | HTTP | Route |
 * | Get All | GET | /api/{Controller}/Get |
 * | Get By ID | GET | /api/{Controller}/GetByID/{id} |
 * | Add | POST | /api/{Controller}/Add |
 * | Update | PUT | /api/{Controller}/Update |
 * | Delete | DELETE | /api/{Controller}/Delete/{id} |
 *
 * ### JWT
 * 1. POST /api/Login/Login → copy token
 * 2. Authorize in Swagger (paste token only)
 * 3. GET /api/Login/Profile to verify
 *
 * **Student:** yash@gmail.com / 123 | **Admin:** admin / admin123
 * OpenAPI spec version: v1
 */

export * from './academicYearModel';
export * from './apiResult';
export * from './attendanceMarkRequest';
export * from './attendanceStudentItemDto';
export * from './batchModel';
export * from './bloodGroupModel';
export * from './categoryModel';
export * from './classModel';
export * from './classworkAddRequest';
export * from './classworkBulkStatusUpdateRequest';
export * from './classworkStatusUpdateRequest';
export * from './classworkUpdateRequest';
export * from './deleteApiClassDeleteClassParams';
export * from './deleteApiClassDeleteIdParams';
export * from './examDeleteRequest';
export * from './examInsertRequest';
export * from './examUpdateRequest';
export * from './feesDeleteRequest';
export * from './feesInsertRequest';
export * from './feesUpdateRequest';
export * from './forgotPasswordRequest';
export * from './getApiAttendanceGetParams';
export * from './getApiClassworkGetParams';
export * from './getApiHomeworkGetParams';
export * from './getApiNoticeGetParams';
export * from './getApiSchoolGetParams';
export * from './getApiSyllabusGetParams';
export * from './getApiTeacherClassAssignmentGetParams';
export * from './getApiTimetableGetParams';
export * from './homeworkAddRequest';
export * from './homeworkBulkStatusUpdateRequest';
export * from './homeworkStatusUpdateRequest';
export * from './homeworkUpdateRequest';
export * from './leaveApplicationDeleteRequest';
export * from './leaveApplicationInsertRequest';
export * from './leaveApplicationUpdateRequest';
export * from './loginRequest';
export * from './moneyDeleteRequest';
export * from './moneyInsertRequest';
export * from './moneyUpdateRequest';
export * from './noticeAddRequest';
export * from './noticeAttachmentDto';
export * from './noticeDeleteRequestDto';
export * from './noticeUpdateRequestDto';
export * from './notificationDeleteRequest';
export * from './notificationInsertRequest';
export * from './notificationMarkReadRequest';
export * from './notificationUpdateRequest';
export * from './parentDeleteRequest';
export * from './parentsChangePasswordRequest';
export * from './postApiUplodedUploadDocumentBody';
export * from './postApiUplodedUploadImageBody';
export * from './postApiUplodedUploadMultipleFilesBody';
export * from './problemDetails';
export * from './putApiClassworkUpdateParams';
export * from './religionModel';
export * from './resultDeleteRequest';
export * from './resultInsertRequest';
export * from './resultUpdateRequest';
export * from './roleDeleteRequest';
export * from './roleInsertRequest';
export * from './roleRightsDeleteRequest';
export * from './roleRightsInsertRequest';
export * from './roleRightsUpdateRequest';
export * from './roleUpdateRequest';
export * from './schoolInsertRequest';
export * from './schoolStatusChangeRequest';
export * from './schoolUpdateRequest';
export * from './sectionModel';
export * from './studentBlacklistRequest';
export * from './studentChangePasswordRequest';
export * from './studentModel';
export * from './subjectDeleteRequest';
export * from './subjectInsertRequest';
export * from './subjectUpdateRequest';
export * from './syllabusAddRequest';
export * from './syllabusAttachmentDto';
export * from './syllabusDeleteRequest';
export * from './syllabusUpdateRequest';
export * from './teacherAttendanceDeleteRequest';
export * from './teacherAttendanceInsertRequest';
export * from './teacherAttendanceUpdateRequest';
export * from './teacherChangePasswordRequest';
export * from './teacherClassAssignmentAddRequest';
export * from './teacherClassAssignmentRemoveRequest';
export * from './teacherClassAssignmentUpdateRequest';
export * from './teacherDeleteRequest';
export * from './teacherInsertRequest';
export * from './teacherUpdateRequest';
export * from './timetableAddRequest';
export * from './timetableBulkAddRequest';
export * from './timetableDeleteRequest';
export * from './timetablePeriodInputDto';
export * from './timetableUpdateRequest';
export * from './userDeleteRequest';
export * from './userDeviceTokenDeleteRequest';
export * from './userDeviceTokenInsertRequest';
export * from './userDeviceTokenUpdateRequest';
export * from './userInsertRequest';
export * from './userUpdateRequest';
