/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * School Management API
 * OpenAPI spec version: v1
 */

export interface LoginModel {
  userId?: number;
  roleId?: number;
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  emailAddress?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
}
