/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * SchoolERP.API
 * ### JWT
 * 1. POST /api/Login/Login → copy token
 * 2. Authorize in Swagger (paste token only)
 * 3. GET /api/Login/Profile to verify
 *
 * **Student:** yash@gmail.com / 123 | **Admin:** admin / admin123
 * OpenAPI spec version: v1
 */

export interface LoginResponseModel {
  userID?: number;
  roleID?: number;
  /** @nullable */
  roleName?: string | null;
  /** @nullable */
  userType?: string | null;
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  mobileNo?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  token?: string | null;
  /** @nullable */
  refreshToken?: string | null;
  /** @nullable */
  profileImage?: string | null;
  /** @nullable */
  permissions?: string[] | null;
}
