/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * SchoolERP.API
 * ### JWT
 * 1. POST /api/Login/Login → copy token
 * 2. Authorize in Swagger (paste token only)
 * 3. GET /api/Login/Profile to verify
 *
 * **Student:** yash@gmail.com / 123 | **Admin:** admin / admin123
 * OpenAPI spec version: v1
 */

export interface MessageModel {
  /** @nullable */
  toMobile?: string | null;
  /** @nullable */
  toEmail?: string | null;
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  body?: string | null;
  /** @nullable */
  channel?: string | null;
}
