/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * School Management API
 * ### API flow (all modules)
 * | Action | HTTP | Route |
 * | Get All | GET | /api/{Controller}/Get |
 * | Get By ID | GET | /api/{Controller}/GetByID/{id} |
 * | Add | POST | /api/{Controller}/Add |
 * | Update | PUT | /api/{Controller}/Update |
 * | Delete | DELETE | /api/{Controller}/Delete/{id} |
 *
 * ### JWT
 * 1. POST /api/Login/Login → copy token
 * 2. Authorize in Swagger (paste token only)
 * 3. GET /api/Login/Profile to verify
 *
 * **Login body:** { "userName": "superadmin", "password": "123" }
 * OpenAPI spec version: v1
 */
import type { NoticeAttachmentDto } from './noticeAttachmentDto';

export interface NoticeUpdateRequestDto {
  noticeID?: number;
  /** @nullable */
  noticeTitle?: string | null;
  /** @nullable */
  noticeDescription?: string | null;
  /** @nullable */
  noticeType?: string | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  attachments?: NoticeAttachmentDto[] | null;
  /** @nullable */
  classIDs?: number[] | null;
  /** @nullable */
  teacherIDs?: number[] | null;
  updatedBy?: number;
  /** @nullable */
  updatedByRole?: string | null;
  replaceAttachments?: boolean;
  replaceAudience?: boolean;
}
