/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * SchoolERP.API
 * ### JWT
 * 1. POST /api/Login/Login → copy token
 * 2. Authorize in Swagger (paste token only)
 * 3. GET /api/Login/Profile to verify
 *
 * **Student:** yash@gmail.com / 123 | **Admin:** admin / admin123
 * OpenAPI spec version: v1
 */

export interface OnlineInquiryModel {
  inquiryID?: number;
  /** @nullable */
  studentName?: string | null;
  /** @nullable */
  parentName?: string | null;
  /** @nullable */
  mobile?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  classID?: number | null;
  /** @nullable */
  medium?: string | null;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  className?: string | null;
  /** @nullable */
  createdOn?: string | null;
}
