/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * School Management API
 * ### API flow (all modules)
 * | Action | HTTP | Route |
 * | Get All | GET | /api/{Controller}/Get |
 * | Get By ID | GET | /api/{Controller}/GetByID/{id} |
 * | Add | POST | /api/{Controller}/Add |
 * | Update | PUT | /api/{Controller}/Update |
 * | Delete | DELETE | /api/{Controller}/Delete/{id} |
 *
 * ### JWT
 * 1. POST /api/Login/Login → copy token
 * 2. Authorize in Swagger (paste token only)
 * 3. GET /api/Login/Profile to verify
 *
 * **Student:** yash@gmail.com / 123 | **Admin:** admin / admin123
 * OpenAPI spec version: v1
 */

export interface ParentUpdateRequest {
  /** @nullable */
  fatherName?: string | null;
  /** @nullable */
  motherName?: string | null;
  /** @nullable */
  fatherMobileNo?: string | null;
  /** @nullable */
  motherMobileNo?: string | null;
  /** @nullable */
  fatherEmail?: string | null;
  /** @nullable */
  motherEmail?: string | null;
  /** @nullable */
  fatherOccupation?: string | null;
  /** @nullable */
  motherOccupation?: string | null;
  /** @nullable */
  address?: string | null;
  roleID?: number;
  createdBy?: number;
  parentID?: number;
  updatedBy?: number;
}
