/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * School Management API
 * OpenAPI spec version: v1
 */

export interface SectionModel {
  sectionID?: number;
  /** @nullable */
  sectionName?: string | null;
}
