/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * School Management API
 * ### API flow (all modules)
 * | Action | HTTP | Route |
 * | Get All | GET | /api/{Controller}/Get |
 * | Get By ID | GET | /api/{Controller}/GetByID/{id} |
 * | Add | POST | /api/{Controller}/Add |
 * | Update | PUT | /api/{Controller}/Update |
 * | Delete | DELETE | /api/{Controller}/Delete/{id} |
 *
 * ### JWT
 * 1. POST /api/Login/Login → copy token
 * 2. Authorize in Swagger (paste token only)
 * 3. GET /api/Login/Profile to verify
 *
 * **Student:** yash@gmail.com / 123 | **Admin:** admin / admin123
 * OpenAPI spec version: v1
 */

export interface StudentModel {
  studentID?: number;
  schoolID?: number;
  academicYearID?: number;
  classID?: number;
  /** @nullable */
  batchID?: number | null;
  /** @nullable */
  sectionID?: number | null;
  /** @nullable */
  studentGRNo?: string | null;
  /** @nullable */
  uidNo?: string | null;
  /** @nullable */
  rollNo?: string | null;
  /** @nullable */
  hallTicketNo?: string | null;
  /** @nullable */
  admissionFormNo?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  middleName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  firstNameSecondary?: string | null;
  /** @nullable */
  middleNameSecondary?: string | null;
  /** @nullable */
  lastNameSecondary?: string | null;
  /** @nullable */
  studentDisplayName?: string | null;
  /** @nullable */
  studentNumber?: string | null;
  /** @nullable */
  studentWhatsappNo?: string | null;
  /** @nullable */
  studentEmail?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  dob?: string | null;
  /** @nullable */
  age?: number | null;
  bloodGroupID?: number;
  /** @nullable */
  bloodGroupName?: string | null;
  /** @nullable */
  birthPlace?: string | null;
  /** @nullable */
  birthPlaceTaluka?: string | null;
  /** @nullable */
  birthPlaceDistrict?: string | null;
  religionID?: number;
  /** @nullable */
  religionName?: string | null;
  /** @nullable */
  nationality?: string | null;
  categoryID?: number;
  /** @nullable */
  categoryName?: string | null;
  /** @nullable */
  caste?: string | null;
  /** @nullable */
  subCaste?: string | null;
  /** @nullable */
  aadhaarNo?: string | null;
  /** @nullable */
  penNo?: string | null;
  /** @nullable */
  aparID?: string | null;
  /** @nullable */
  gender?: string | null;
  /** @nullable */
  weight?: number | null;
  /** @nullable */
  height?: number | null;
  /** @nullable */
  ews?: boolean | null;
  /** @nullable */
  currentAddress?: string | null;
  /** @nullable */
  currentCity?: string | null;
  /** @nullable */
  sameAsCurrentAddress?: boolean | null;
  /** @nullable */
  permanentAddress?: string | null;
  /** @nullable */
  permanentCity?: string | null;
  /** @nullable */
  transportFacility?: boolean | null;
  /** @nullable */
  studentFeesDate?: string | null;
  /** @nullable */
  admissionDate?: string | null;
  /** @nullable */
  admissionYear?: string | null;
  /** @nullable */
  previousSchoolName?: string | null;
  /** @nullable */
  previousSchoolCategory?: string | null;
  /** @nullable */
  previousSchoolCityVillage?: string | null;
  /** @nullable */
  mediumID?: number | null;
  /** @nullable */
  mediumName?: string | null;
  /** @nullable */
  lastSchoolType?: string | null;
  /** @nullable */
  previousSchoolType?: string | null;
  /** @nullable */
  lastSemesterYearPercentage?: number | null;
  /** @nullable */
  referenceSource?: string | null;
  /** @nullable */
  siblingInfo?: string | null;
  /** @nullable */
  remarks?: string | null;
  /** @nullable */
  studentType?: string | null;
  /** @nullable */
  studentShift?: string | null;
  /** @nullable */
  admissionStandard?: string | null;
  /** @nullable */
  rte?: boolean | null;
  /** @nullable */
  parentUserName?: string | null;
  /** @nullable */
  parentPassword?: string | null;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  createdDate?: string | null;
  /** @nullable */
  fatherName?: string | null;
  /** @nullable */
  fatherNumber?: string | null;
  /** @nullable */
  fatherOccupation?: string | null;
  /** @nullable */
  fatherEducation?: string | null;
  /** @nullable */
  fatherEmail?: string | null;
  /** @nullable */
  motherName?: string | null;
  /** @nullable */
  motherNumber?: string | null;
  /** @nullable */
  motherOccupation?: string | null;
  /** @nullable */
  motherEducation?: string | null;
  /** @nullable */
  motherEmail?: string | null;
  /** @nullable */
  whatsappNumber?: string | null;
  /** @nullable */
  sendSMSNotification?: boolean | null;
  /** @nullable */
  studentPhoto?: string | null;
  /** @nullable */
  fatherPhoto?: string | null;
  /** @nullable */
  motherPhoto?: string | null;
  /** @nullable */
  isActive?: boolean | null;
  /** @nullable */
  createdBy?: number | null;
  /** @nullable */
  updatedBy?: number | null;
  /** @nullable */
  blacklistReason?: string | null;
  /** @nullable */
  blacklistedOn?: string | null;
  /** @nullable */
  blacklistedBy?: number | null;
}
