/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * School Management API
 * OpenAPI spec version: v1
 */

export interface StudentModel {
  studentID?: number;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  studentDisplayName?: string | null;
  /** @nullable */
  rollNo?: string | null;
  /** @nullable */
  studentGRNo?: string | null;
  /** @nullable */
  studentEmail?: string | null;
  /** @nullable */
  studentNumber?: string | null;
  classID?: number;
  /** @nullable */
  sectionID?: number | null;
  /** @nullable */
  batchID?: number | null;
  /** @nullable */
  admissionYear?: string | null;
  /** @nullable */
  dob?: string | null;
  /** @nullable */
  gender?: string | null;
  /** @nullable */
  currentAddress?: string | null;
}
