/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * SchoolERP.API
 * ### JWT
 * 1. POST /api/Login/Login → copy token
 * 2. Authorize in Swagger (paste token only)
 * 3. GET /api/Login/Profile to verify
 *
 * **Student:** yash@gmail.com / 123 | **Admin:** admin / admin123
 * OpenAPI spec version: v1
 */

export interface StudentHistoryModel {
  historyID?: number;
  studentID?: number;
  /** @nullable */
  academicYearID?: number | null;
  /** @nullable */
  classID?: number | null;
  /** @nullable */
  sectionID?: number | null;
  /** @nullable */
  remarks?: string | null;
  /** @nullable */
  changedBy?: number | null;
  /** @nullable */
  changedOn?: string | null;
  /** @nullable */
  academicYearName?: string | null;
  /** @nullable */
  className?: string | null;
  /** @nullable */
  sectionName?: string | null;
}
