/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * School Management API
 * ### API flow (all modules)
 * | Action | HTTP | Route |
 * | Get All | GET | /api/{Controller}/Get |
 * | Get By ID | GET | /api/{Controller}/GetByID/{id} |
 * | Add | POST | /api/{Controller}/Add |
 * | Update | PUT | /api/{Controller}/Update |
 * | Delete | DELETE | /api/{Controller}/Delete/{id} |
 *
 * ### JWT
 * 1. POST /api/Login/Login → copy token
 * 2. Authorize in Swagger (paste token only)
 * 3. GET /api/Login/Profile to verify
 *
 * **Login body:** { "userName": "superadmin", "password": "123" }
 * OpenAPI spec version: v1
 */

export interface StudentSearchRequest {
  /**
     * @minimum 1
     * @maximum 2147483647
     */
  page?: number;
  /**
     * @minimum 1
     * @maximum 100
     */
  pageSize?: number;
  /** @nullable */
  search?: string | null;
  /** @nullable */
  classID?: number | null;
  /** @nullable */
  batchID?: number | null;
  /** @nullable */
  mediumID?: number | null;
  /** @nullable */
  sectionID?: number | null;
  /** @nullable */
  academicYearID?: number | null;
  /** @nullable */
  gender?: string | null;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  sortBy?: string | null;
  /** @nullable */
  sortOrder?: string | null;
}
