/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * School Management API
 * ### API flow (all modules)
 * | Action | HTTP | Route |
 * | Get All | GET | /api/{Controller}/Get |
 * | Get By ID | GET | /api/{Controller}/GetByID/{id} |
 * | Add | POST | /api/{Controller}/Add |
 * | Update | PUT | /api/{Controller}/Update |
 * | Delete | DELETE | /api/{Controller}/Delete/{id} |
 *
 * ### JWT
 * 1. POST /api/Login/Login → copy token
 * 2. Authorize in Swagger (paste token only)
 * 3. GET /api/Login/Profile to verify
 *
 * **Login body:** { "userName": "superadmin", "password": "123" }
 * OpenAPI spec version: v1
 */
import type { SyllabusAttachmentDto } from './syllabusAttachmentDto';

export interface SyllabusAddRequest {
  /** @nullable */
  schoolID?: number | null;
  classID?: number;
  /** @nullable */
  batchID?: number | null;
  /** @nullable */
  studentIDs?: number[] | null;
  subjectID?: number;
  /** @nullable */
  syllabusTitle?: string | null;
  /** @nullable */
  syllabusDescription?: string | null;
  releaseDate?: string;
  /** @nullable */
  releaseTime?: string | null;
  /** @nullable */
  attachments?: SyllabusAttachmentDto[] | null;
}
