/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * School Management API
 * ### API flow (all modules)
 * | Action | HTTP | Route |
 * | Get All | GET | /api/{Controller}/Get |
 * | Get By ID | GET | /api/{Controller}/GetByID/{id} |
 * | Add | POST | /api/{Controller}/Add |
 * | Update | PUT | /api/{Controller}/Update |
 * | Delete | DELETE | /api/{Controller}/Delete/{id} |
 *
 * ### JWT
 * 1. POST /api/Login/Login → copy token
 * 2. Authorize in Swagger (paste token only)
 * 3. GET /api/Login/Profile to verify
 *
 * **Login body:** { "userName": "superadmin", "password": "123" }
 * OpenAPI spec version: v1
 */

export interface TeacherUpdateRequest {
  /** @nullable */
  teacherCode?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  middleName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  mobileNo?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  gender?: string | null;
  /** @nullable */
  qualification?: string | null;
  experienceYear?: number;
  joiningDate?: string;
  salary?: number;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  subjectName?: string | null;
  roleID?: number;
  /** @nullable */
  photo?: string | null;
  createdBy?: number;
  teacherID?: number;
  updatedBy?: number;
}
